
repos:
  - repo: https://github.com/python/black
    rev: 22.3.0
    hooks:
      - id: black
        args:
          - --check
          - -v
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-docstring-first
      - id: mixed-line-ending
  - repo: https://github.com/pycqa/pylint
    rev: v3.1.0
    hooks:
      - id: pylint
        name: pylint (library code)
        types: [python]
        args:
          #- --rcfile=.pylintrc
          - --disable=consider-using-f-string,duplicate-code
        exclude: "^(docs/|examples/|tests/|setup.py$)"
      - id: pylint
        name: pylint (example code)
        description: Run pylint rules on "examples/*.py" files
        types: [python]
        files: "^examples/"
        args:
          - --disable=missing-docstring,invalid-name,consider-using-f-string,duplicate-code
      - id: pylint
        name: pylint (test code)
        description: Run pylint rules on "tests/*.py" files
        types: [python]
        files: "^tests/"
        args:
          - --disable=missing-docstring,consider-using-f-string,duplicate-code
