
[project]
name = "sierralobo-circuitpython-mc3419"
description = "Accelerometer sensor library"
version = "0.0.0+auto.0"
readme = "README.md"
authors = [
    {name = "Caden Hillis"}
]

[project.urls]
Homepage = "https://github.com/Sierra-Lobo/Adafruit_CircuitPython_MMC56x3"
